{{- if .Values.metrics.enabled -}}
{{- $chart := "mail" -}}
{{- $fullName := include (print $chart ".fullname") . -}}
{{- $labels := include (print $chart ".labels") . -}}
{{- $selectorLabels := include (print $chart ".selectorLabels") . -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mail-metrics
  labels:
    {{- $labels | nindent 4 }}
    {{- with .Values.service.labels }}{{ toYaml . | nindent 4 }}{{ end }}
  annotations:
    {{- with .Values.service.annotations }}{{ toYaml . | nindent 4 }}{{ end }}
spec:
  endpoints:
  - interval: 15s
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $chart }}
      prometheus: unknown
{{- end -}}
