dns:
  policy: "None"
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"
  searches:
    - default.svc.cluster.local 
    - svc.cluster.local 
    - cluster.local
  options:
    - name: ndots
      value: "5"
    - name: edns0
